version: '3.1'
services:
  stats-server:
    build: stats-server/server/
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
          - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ltsg-stats
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root

  stats-db:
    image: postgres:16-alpine
    container_name: postgres-stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=stats

  ewm-service:
    build: ltsg-server
    image: ltsg-server
    container_name: ltsg-server
    ports:
      - "8080:8080"
    depends_on:
      - main-db
    environment:
      - GOOGLE_API_KEY=AIzaSyBJkzcFuwZ3LlsSX_ruNYOj8hNT9aa92_w
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/ltsg-main
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root

  main-db:
    image: postgres:16-alpine
    container_name: postgres-main-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
